name: wordle_ultimate_server
description: The backend server for the Wordle Ultimate game, built with Dart Frog.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0
  supabase: ^2.5.0
  dotenv: ^4.2.0
  uuid: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0