# .github/workflows/cd.yml

name: Continuous Deployment

# This workflow runs only when code is pushed to the `main` branch
on:
  push:
    branches: [ "main" ]

jobs:
  # Job to build and push the backend Docker image and then deploy it
  deploy-server:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push images to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the root directory as context
          file: ./Dockerfile # Specify the Dockerfile location
          push: true
          tags: ghcr.io/${{ github.repository }}/wordle-ultimate-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- DEPLOYMENT STEP ---
      # The step below is a placeholder. You would replace this with the
      # specific deployment action for your chosen hosting provider (e.g., Fly.io, Render).
      # - name: Deploy to Fly.io
      #   uses: superfly/fly-pr-actions/setup-flyctl@master
      # - run: flyctl deploy --remote-only --dockerfile Dockerfile
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
